<a href="https://colab.research.google.com/github/Chen-Mei-Chen/Python_Self_Learning/blob/main/%3CPython%E7%AD%86%E8%A8%98%3ENumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

>本筆記本是一個自學者的筆記
>
>當時搭配的資源: [點此](https://youtube.com/playlist?list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&feature=shared) (內部的程式碼不少與之雷同，故可直接在本notebook進行實驗)

### **Numpy是甚麼**

Numpy基本上就是矩陣的計算工具，常用於機器學習、數據分析領域

首先在IDE中要先pip instal numpy

In [ ]:
import numpy as np

#這是示範印出矩陣功能:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

#數出矩陣有多少元素:
print(np1.shape)

#從0到9的數字矩陣
np2 = np.arange(10)
print(np2)
#一樣，不過step=2
np3 = np.arange(0,10,2)
print(np3)

#創造十個0.
np4 = np.zeros(10)
print(np4)

'''以上都是一維的矩陣陣列，接下來我們試著創造二維的0矩陣:'''

#創造兩行10個的0:
np5 = np.zeros((2,10)) #這邊記得雙括號
print(np5)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


以上是有關array、arange、zeros函數的介紹，其實有一個函數叫做:full可以取代上面這一切

比方說full函數可以:
* 印出十個6，而不僅限於0
* 印出兩行十個6

In [ ]:
np6 = np.full((10),6)
print(np6)

np7 = np.full((2,10),6)
print(np7)

[6 6 6 6 6 6 6 6 6 6]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


### **numpy跟list的差異?**


* numpy一次只能儲存單一形式的資料型態，而list可以讓數字、字串、布林值共存
  
* numpy可處理多維矩陣運算，而list基本上還要編寫for迴圈去做巢狀結構


不過，兩者之間不只相似，還可以互相互動

比方說:我們可以先用list自訂array值，送進numpy，然後numpy的矩陣中的元素也可以用0~n的序號訪問

In [ ]:
#先用list自訂array值，送進numpy
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)

#numpy的矩陣中的元素也可以用0~n的序號訪問
print(np8[0]) #記得，是用中括號
print(np8[0:2])
print(np8[2:])
print(np8[-3:-1])

[1 2 3 4 5]
1
[1 2]
[3 4 5]
[3 4]


In [ ]:
'''序號訪問結合step:'''
#[1,2,3,4,5]

#印出第1到3的序號，不過step=2
print(np8[1:4:2])

#整個矩陣下去step:
print(np8[::2])

[2 4]
[1 3 5]


我們已經熟悉一維陣列的基礎，接下來看

**二維的序列呼叫:**

In [ ]:
np2d = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #記得兩層中括號
print(np2d[1,2])
#由此看出，1指的是序列1的列，2是該序列的第二個元素，因此返回8

#也可以用序列方法一次返回包含的子矩陣
print(np2d[0:2,1:3])
#翻譯:序號0到1的列中的1到2項

8
[[2 3]
 [7 8]]


### **Numpy的威力-自動遍歷的數學**

以前要讓所有數據進行運算，需要使用for迴圈，現在numpy有各種函式對矩陣內所有元素進行運算:

In [ ]:
#[[1,2,3,4,5],[6,7,8,9,10]]

#把所有元素開根號:
print(np.sqrt(np2d))

#絕對值:
print(np.absolute(np2d))

#e的幾次方
print(np.exp(np2d))

#找最大最小值:
print(np.max(np2d))

#把所有正數代換成1，負數代換成-1，0還是0:
print(np.sign(np2d))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]]
10
[[1 1 1 1 1]
 [1 1 1 1 1]]


當然，不是只有這樣，還有sin、cos、log...

可以上 Numpy universal function docs 查看更多，或是把整個網站餵給AI叫它找

### **view vs copy**

np.view是一種共享記憶體的形式，假設b=a.view()，日後a的資料被修改，b也會一起被更動

np.copy則使用獨立的記憶體，日後a被修改，b會維持原本的樣子

In [ ]:
#共患難的view:

a = np.array([1, 2, 3])
b = a.view()
b[0] = 100

print(a)
print(b)

[100   2   3]
[100   2   3]


In [ ]:
#各自獨立的copy:

c = a.copy()
c[0] = 999

print(a)
print(c)


[100   2   3]
[999   2   3]


### **shape & reshape**

shape函數可以說是描繪出矩陣的形狀，而reshape則是用形狀建造出實際的矩陣

In [ ]:
#描繪矩陣形狀的shape:

#一維:
npa = np.array([1,2,3,4,5,6,7,8])
print(npa.shape) #須注意，不是shape()

#二維:
npa2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(npa2d.shape)
#可以看到結果會顯示它是幾乘幾的矩陣

(8,)
(2, 5)


In [ ]:
#用形狀建立矩陣的reshape

#二維:
npc = npa.reshape(2,4)
print(npc)

#三維:有"高"的概念，會把每一個二維層切開展示
npd = npa.reshape(2,2,2)
print(npd)

#從n維降到一維
npe = npd.reshape(-1) #填入維度
print(npe)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


### **矩陣內部的遍歷:**

In [ ]:
#一維遍歷

np1 = np.array([1,2,3,4,5])
for x in np1:
    print(x)

1
2
3
4
5


In [ ]:
#二維遍歷

#第一次遍歷，只會把所有的"列"都秀出來，如下:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
    print(x)

#所以要再加一層，如下:
for x in np2:
    for y in x:
        print(y)

[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10


In [ ]:
#三維遍歷

np3 = np.array([[[1,2,3],
                [4,5,6]],
               [[7,8,9],
               [10,11,12]]])
#當然，也可以橫的打，只是容易錯亂[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
for x in np3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


但，這未免太麻煩了，使用nditer函式只需迭代一次就行，不限任何維度!

In [ ]:
#使用nditer:

for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


### **讓矩陣重新排列-Sort函數:**

In [ ]:
#排序矩陣:
np1 = np.array([2,5,3,1,7,0])
print(np.sort(np1))

#其他像是字串、布林值的矩陣，就是從字母a排到z、從false排到true(不奇怪，就是0排到1的概念)

#甚至連二維都可以對每個列中的元素進行排序:
np2 = np.array([[1,5,3],[2,6,0]])
print(np.sort(np2))

[0 1 2 3 5 7]
[[1 3 5]
 [0 2 6]]


### **搜尋矩陣裡面的元素-where函式:**

In [ ]:
#尋找矩陣裡的單一元素，並返回該序列+資料的型態
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.where(np1 == 3)
print(x)

(array([2]),)


一般來說，會輸出:(array(\[2],dtype = int64),)

對，這是一個格式奇怪的tuple，只是不知為何kaggle沒有顯示出後面那一項


不過有時我們不需要這種tuple形式的回傳，有時我們只想:
* 只給出序列值即可
* 只給出資料型態即可

則，我們可以指定我們要tuple的哪一項:

In [ ]:
#以只給出序列值為例:

print(x[0]) #因為x=(array([2],dtype = int64),)，取第0項

'''如果一個矩陣有兩個3，也有一樣效果'''
np2 = np.array([1,2,3,4,5,6,7,8,9,10,3])
y = np.where(np2 == 3)
print(y[0])

[2]
[ 2 10]


如果，我們想查看矩陣中"所有的3"，而不是3所在的"序號"的話，可以這樣寫:

這樣寫的邏輯在於，**y\[0]** 會返回3所處的所有序號，然而還記得嗎? **np2\[序號]** 可返回對應的值，所以用此方法，可以找到所有的3本尊

In [ ]:
print(np2[y[0]])

[3 3]


**結合數學-用where找出特定規則的值**

基本上，在where內部填入關係式，where就會找出符合關係式的值

以下以"找出所有偶數"為例:

In [ ]:
z = np.where(np1 % 2 == 0)
print(z[0])      #返回所有偶數對應的序號
print(np1[z[0]]) #返回所有偶數值的值

[1 3 5 7 9]
[ 2  4  6  8 10]


### **矩陣元素篩選**

用以下方法可以篩選出想要的特定值:

In [ ]:
#利用布林值篩選想要的值
np1 = np.array([1,2,3,4,5])
x = [True,False,True,False,False]
print(np1[x])

[1 3]


但...我們怎麼可能一個一個打布林值?

因此需要結合for迴圈，引進filter技術:

In [ ]:
#以篩選出偶數值為例:

filtered = [] #這是在令一個空矩陣，用來存放我們等等過濾的值，不一定要命名為filtered
for i in np1:
    if i % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)
print(np1[filtered])

[2 4]


In [ ]:
#更簡潔的寫法:

filtered2 = np1 % 2 == 0
print(filtered2)

#可以看見這樣返回的是布林值!因此要寫成:
print(np1[filtered2])

[False  True False  True False]
[2 4]


無論是用哪種方法，我們日後都可以用各種關係式、條件，來判斷矩陣內的元素是否符合(True)或不符合(False)這條關係式，進而對其採取動作，可以說這個世界是由布林值所組成一點也不為過。